Fix app x509 sign sm2 cert bug
BabaSSL/BabaSSL pull request #236
Opened 2022-05-07 02:46 UTC by dongbeiouba

Fix #235 

Should set X509 info before sign sm2 cert.

##### Checklist

- [ ] 增加或更新了必要的文档（包括readthedocs上）
- [ ] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-05-07 02:50 UTC, InfoHunter requested changes
需增加测试用例

2022-05-09 02:14 UTC, dongbeiouba commented
ping @InfoHunter @jinjiu

2022-05-09 02:15 UTC, jinjiu approved these changes

2022-05-10 03:40 UTC, InfoHunter approved these changes

2022-05-10 03:40 UTC, merged