Support new feature: add export symbol prefix
BabaSSL/BabaSSL pull request #256
Opened 2022-07-16 01:59 UTC by jinjiu

If the parameter --symbol-prefix=BABA_ is configured, the prefix BABA_ will be
added to the exported symbols of dynamic libraries (libssl.so, libcrypto.so)
and static libraries (libssl.a, libcrypto.a), and then the corresponding macros
are used to conversion (in file: include/openssl/symbol_prefix.h) to keep the
interface compatible.

##### Checklist

- [ ] 增加或更新了必要的文档（包括readthedocs上）
- [ ] 增加或更新了必要的测试用例
- [x] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-07-18 22:54 UTC, InfoHunter approved these changes

2022-07-19 05:14 UTC, dongbeiouba reviewed
1.已经在头文件中声明的符号，就不用在新加的头文件中重复声明了。
2.增加的头文件如果只用于符号搜所的话，而不会用于include，那就没必要搞成.h文件，是不是可以改成.txt文件？类似于util下missingssl.txt，然后只要把函数名放到里面即可，不需要完整的函数声明。符号搜所时从这个文件中找就好了,这样.c文件不用修改，.h文件也不用增加

2022-07-19 05:14 UTC, dongbeiouba commented on util/mk_symbol_prefix.pl
> +	my($files, $debug, $trace, $verbose) = @_;
对齐问题，下同

2022-07-19 05:14 UTC, dongbeiouba commented on crypto/md5/md5_dgst.c
> +#ifndef ASM_md5_block_data_order
改成如果未定义ASM_md5_block_data_order则定义md5_block_data_order，跟原意不一样了

2022-07-19 05:14 UTC, dongbeiouba commented on crypto/md4/md4_dgst.c
> +#ifndef ASM_md4_block_data_order
改成如果未定义ASM_md4_block_data_order则定义md4_block_data_order，跟原意不一样了

2022-07-20 09:06 UTC, jinjiu commented on util/mk_symbol_prefix.pl
> +    "HWSM4_set_encrypt_key" => 1,
> 为啥HWSM4_相关的函数要ignore？

已适配和删除

2022-07-20 09:06 UTC, jinjiu commented on util/mk_symbol_prefix.pl
> +	$debug=1 if $_ eq "debug";
> 对齐问题，下同

已修复

2022-07-20 09:06 UTC, jinjiu commented on util/mk_symbol_prefix.pl
> +	my($files, $debug, $trace, $verbose) = @_;
> 对齐问题，下同

已修复

2022-07-20 09:13 UTC, jinjiu commented
> 1.已经在头文件中声明的符号，就不用在新加的头文件中重复声明了。 2.增加的头文件如果只用于符号搜所的话，而不会用于include，那就没必要搞成.h文件，是不是可以改成.txt文件？类似于util下missingssl.txt，然后只要把函数名放到里面即可，不需要完整的函数声明。符号搜所时从这个文件中找就好了,这样.c文件不用修改，.h文件也不用增加

目前加这个还只是适配历史遗留的在.c 文件中声明的函数和全局变量，以后新增的函数和全局变量会尽量在自己的头文件中声明，也会自动被 perl 脚本解析，.h 文件本来就是用来放声明的地方，即使被 include 也可以（只是目前为了减少 diff，没有把声明的地方删除后 include 该文件），单独搞一个类似 missingssl.txt 的文件反而比较重。

2022-07-20 11:03 UTC, dongbeiouba requested changes
对齐问题

2022-07-20 11:03 UTC, dongbeiouba commented on util/perl/OpenSSL/Symbol.pm
> +	my($name, $files, $symhacksfile, $debug, $trace, $verbose) = @_;
对齐问题

2022-07-20 11:03 UTC, dongbeiouba commented on util/perl/OpenSSL/Symbol.pm
> +			my ($s, $a, $p, $k) = @_;
对齐问题

2022-07-20 11:03 UTC, dongbeiouba commented on util/perl/OpenSSL/Symbol.pm
> +	(my $symbol, my $exist, my $platforms, my $kind, my $algorithms) = @_;
对齐问题，下同

2022-07-21 01:34 UTC, jinjiu commented on crypto/local.h
> +void OPENSSL_cpuid_setup(void);
> include/internal/cryptlib.h已经声明了OPENSSL_cpuid_setup()

已删

2022-07-21 01:35 UTC, jinjiu commented on util/perl/OpenSSL/Symbol.pm
> +			my ($s, $a, $p, $k) = @_;
> 对齐问题

已修复

2022-07-21 01:35 UTC, jinjiu commented on util/perl/OpenSSL/Symbol.pm
> +	(my $symbol, my $exist, my $platforms, my $kind, my $algorithms) = @_;
> 对齐问题，下同

已修复

2022-07-25 02:33 UTC, InfoHunter approved these changes

2022-07-25 02:33 UTC, merged