NTLS允许设置security level和proto version
BabaSSL/BabaSSL pull request #310
Opened 2022-10-02 08:39 UTC by yangboyd

NTLS允许设置security level和proto version
    SSL_CTX_set_security_level(ctx, 2);
    SSL_CTX_set_min_proto_version(ctx, NTLS1_1_VERSION);
    SSL_CTX_set_max_proto_version(ctx, NTLS1_1_VERSION);

2022-10-02 08:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Tongsuo-Project/Tongsuo?pullRequest=310) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Tongsuo-Project/Tongsuo?pullRequest=310) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Tongsuo-Project/Tongsuo?pullRequest=310) it.</sub>

2022-10-09 06:38 UTC, wa5i requested changes

2022-10-09 06:38 UTC, wa5i commented on ssl/ssl_cert.c
> +                if(level > 3)
这几行可以合并为一行：return level > 3 ? 0 : 1;

2022-10-09 06:38 UTC, wa5i commented on ssl/ssl_cert.c
> +                //In addition to the level 2 exclusions cipher suites not offering forward secrecy are prohibited. TLS versions below 1.1 are not permitted. Session tickets are disabled.
这几行注释换成多行注释，并控制单行宽度不要超过80字符宽

2022-10-09 06:38 UTC, wa5i commented on ssl/ssl_cert.c
> +            if (nid == NTLS_VERSION)
注意编码规范，if 和 { 在一行，不是两行

2022-10-10 05:02 UTC, yangboyd commented on ssl/ssl_cert.c
> +                if(level > 3)
多谢提示，已改正

2022-10-10 05:02 UTC, yangboyd commented on ssl/ssl_cert.c
> +                //In addition to the level 2 exclusions cipher suites not offering forward secrecy are prohibited. TLS versions below 1.1 are not permitted. Session tickets are disabled.
多谢提示，已改正

2022-10-10 05:02 UTC, yangboyd commented on ssl/ssl_cert.c
> +            if (nid == NTLS_VERSION)
多谢提示，已改正

2022-10-13 03:38 UTC, wa5i commented on ssl/ssl_cert.c
> +            if (nid == NTLS_VERSION)  {
)和{的空格只需一个。
上面的注释不符合编码规范，请参考：https://www.yuque.com/tsdoc/misc/fbr03n。

2022-10-14 00:22 UTC, yangboyd commented on ssl/ssl_cert.c
> +            if (nid == NTLS_VERSION)  {
谢谢，已改正

2022-10-14 08:24 UTC, wa5i reviewed
LGTM. 
ping @InfoHunter @dongbeiouba

2022-10-14 08:37 UTC, InfoHunter approved these changes

2022-10-14 08:37 UTC, InfoHunter commented
@wa5i 你需要aprrove，不然现在处于是requested changes状态

2022-10-14 08:43 UTC, dongbeiouba requested changes

2022-10-14 08:43 UTC, dongbeiouba commented on ssl/ssl_cert.c
> +            /*-
注释格式不对，SSL_CTX_set_security_level的接口说明删除吧

2022-10-14 08:43 UTC, dongbeiouba commented on ssl/ssl_cert.c
> +                return level > 3 ? 0 : 1;
我理解level >= 3返回0

2022-10-14 08:46 UTC, wa5i approved these changes

2022-10-18 02:39 UTC, yangboyd commented on ssl/ssl_cert.c
> +            /*-
这个地方对之前的判断有改动，注释说明了为什么level 3的情况返回1。因为level 3要求ECC密钥至少256位，而国密SSL证书的sm2采用256位密码长度，加密强度等同于3072位RSA证书，所以满足SSL安全等级level 3的要求。

2022-10-18 02:40 UTC, yangboyd commented on ssl/ssl_cert.c
> +                return level > 3 ? 0 : 1;
对于NTLS国密协议，level >3返回0; level<=3是适合的，所以返回1. 因为level 3要求ECC密钥至少256位，而国密SSL证书的sm2采用256位密码长度，加密强度等同于3072位RSA证书，所以NTLS1.1满足SSL安全等级level 3的要求。

2022-10-18 02:43 UTC, yangboyd commented on ssl/ssl_cert.c
> +            /*-
您看注释哪个地方要再完善一下？

2022-10-19 09:11 UTC, InfoHunter commented on ssl/ssl_cert.c
> +            /*-
注释好像没问题

2022-10-24 01:41 UTC, yangboyd commented
@dongbeiouba 请再review一下

2022-10-24 02:10 UTC, dongbeiouba requested changes

2022-10-24 02:10 UTC, dongbeiouba commented on ssl/ssl_cert.c
> +                return level > 3 ? 0 : 1;
当前的TLCP 1.1并不支持前项安全。

2022-11-02 00:19 UTC, yangboyd commented
请 @dongbeiouba 大佬确认

2022-11-02 02:06 UTC, dongbeiouba commented
> 请 @dongbeiouba 大佬确认

确认啥？还是没有修改。

如果方便的话，也可以进钉钉群，直接聊更高效一些。

2022-11-08 00:55 UTC, yangboyd commented
> > 请 @dongbeiouba 大佬确认
> 
> 确认啥？还是没有修改。
> 
NTLSv1.1协议中的ECDHE-SM2-SM4-CBC-SM3支持前向安全，不用修改？

2022-11-08 04:59 UTC, dongbeiouba requested changes

2022-11-08 04:59 UTC, dongbeiouba commented on ssl/ssl_cert.c
> +            * NTLS v1.1 not suitable for above level 3
就把这一行注释留下就行，其他没必要，删除吧

2023-11-01 08:20 UTC, timonwong commented
只是个人想法，能不能对 TLS 和 NTLS 分别设置呢？

比如一个server，同时支持国际 TLS 和 NTLS。当使用 TLS 时，我希望使用 TLS 1.2+, NTLS 使用 NTLS 1.1 （目前应该完全不能设置 SSL_CTX_set_min_proto_version / SSL_CTX_set_max_proto_version，后续会报 unsupported protocol 错误

```cpp
SSL_CTX_set_min_proto_version(ctx, TLS1_3_VERSION);
SSL_CTX_set_max_proto_version(ctx, TLS1_3_VERSION);

// 然后 NTLS 使用单独的配置
SSL_CTX_set_min_proto_version_ntls(ctx, NTLS1_1_VERSION);
SSL_CTX_set_max_proto_version_ntls(ctx, NTLS1_1_VERSION);
```

2026-03-23 07:09 UTC, closed without merging